### ISSUE TITLE
Network 분류

### ISSUE THREAD

**Issue by jisungbin** [jkey20/Knowledge#2]
안녕하세요!
`NetWork` 폴더에 있는 `RxJava`와 `Coroutine`은, 네트워크 보다는 비동기인 `Asynchrony` 폴더로 구분하는게 더 올바른 분류인거 같습니당

혹시 네트워크로 분류하신 이유가 있을까요?

**Comment by jkey20** [comment]
기존에 네트워크 작업과 관련해서만 RxJava와 코루틴을 썼어서 습관적으로 네트워크라고 이름지었네요 ㅠ
수정해야겠네요 감사합니다!
